In [1]:
import numpy as np

d = np.load("../data/processed/split_scaled.npz", allow_pickle=True)
X_train_s = d["X_train_s"]
X_test_s  = d["X_test_s"]
y_train   = d["y_train"]
y_test    = d["y_test"]


In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, f1_score

clf = LogisticRegression(max_iter=2000)
clf.fit(X_train_s, y_train)

y_pred = clf.predict(X_test_s)

print("F1-macro:", f1_score(y_test, y_pred, average="macro"))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


F1-macro: 0.7227191413237924
[[ 19   1   1]
 [  2   2   6]
 [  1   0 168]]
              precision    recall  f1-score   support

           N       0.86      0.90      0.88        21
           P       0.67      0.20      0.31        10
           Y       0.96      0.99      0.98       169

    accuracy                           0.94       200
   macro avg       0.83      0.70      0.72       200
weighted avg       0.94      0.94      0.93       200



In [3]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

models = {
    "KNN": KNeighborsClassifier(n_neighbors=7),
    "SVM_RBF": SVC(kernel="rbf"),
    "RF": RandomForestClassifier(n_estimators=300, random_state=42)
}

for name, m in models.items():
    m.fit(X_train_s, y_train)
    pred = m.predict(X_test_s)
    print("\n", name)
    print("F1-macro:", f1_score(y_test, pred, average="macro"))



 KNN
F1-macro: 0.8223053969233934

 SVM_RBF
F1-macro: 0.7205248187907148

 RF
F1-macro: 0.9814728561817523
